services:
  - type: web
    name: football-poster-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    pythonVersion: 3.11.9
